default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: book_catalog_development

test:
  <<: *default
  database: book_catalog_test

production:
  primary: &primary_production
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>

  # Reuse the same Heroku Postgres DB for queue, cable, and cache
  queue:
    <<: *primary_production

  cable:
    <<: *primary_production

  cache:
    <<: *primary_production
